task: ISLR
data:
  model_name: UFOneView
  base_url: /home/ibmelab/Documents/GG/VSLRecognition/MM-WLAuslan
  dataset_name: VN_SIGN
  temporal_stride: 2
  num_output_frames: 16
  crop_two_hand: false
  transform_cfg:
    index_setting:
      - segment #train_p
      - pad #train_m
      - segment #test_p
      - pad #test_m
  vid_transform:
    IMAGE_SIZE: 224
    NORM_MEAN_IMGNET: [0.485, 0.456, 0.406]
    NORM_STD_IMGNET: [0.229, 0.224, 0.225]
  SHOULDER_DIST_EPSILON: 1.2
  WRIST_DELTA: 0.15
  label_folder: Label/labelCenterSTU
  # label_folder: Label/labelRightSTU
  # label_folder: Label/labelLeftSTU
  # label_folder: Label/labelCenterITW
  # label_folder: Label/labelRightITW
  # label_folder: Label/labelLeftITW
  # label_folder: Label/labelCenterSYN
  # label_folder: Label/labelRightSYN
  # label_folder: Label/labelLeftSYN
  # label_folder: Label/labelCenterTED
  # label_folder: Label/labelRightTED
  # label_folder: Label/labelLeftTED
  data_type: labels
training:
  test: true
  coefficient:
    cls_x: 1
    cts_x: 1
    cosine_x: 1
  label_smoothing: 0
  mixup: True
  alpha_mixup: 0.8
  device: cuda:0
  overwrite: true
  log_freq: 1
  experiment_name: "UFOneView MMAuslan from K400 (Testing STU)"
  model_dir: results/VTNGCN/vsl
  random_seed: 42
  shuffle: True
  num_workers: 12
  prefetch_factor: 2
  batch_size: 1 #to-debug!
  total_epoch: 300 #to-debug!
  learning_rate: 0.0001
  save_checkpoints: true
  scheduler_factor: 0.1
  scheduler_patience: 5
  plot_loss: true
  plot_lr: true
  plot_acc: true
  criterion: MyCustomLoss
  optimzer: Adam
  lr_scheduler: StepLR
  use_gsam: false
  gsam_alpha: 1.0      
  rho_max: 0.6         
  rho_min: 0.0      
  gsam_adaptive: false
  top_k: 5
  print_stats: true
  pretrained: true
  pretrained_model: None
  lr_step_size: 5
  gamma: 0.8
  num_accumulation_steps: 5
  patience: 20
  verbose: true
  delta: 0
  is_early_stopping: true
  gradient_clip_val: 5
  w_decay: 1e-4
  log_train_step: true
  log_steps: 50
  evaluate_step: 250
  evaluate_strategy: epoch

model:
  num_classes: 3215
  maskFeat: False
  pretraiend: False
  pretrained_name: None


